myfirstflask/models/marker.py
# from geoalchemy2 import Geography
from myfirstflask.app import db

class Marker(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # coordenadas = db.Column(Geography(geometry_type='POINT', srid=SRID), unique=True)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)

    def __init__(self, latitude=None, longitude=None):
        # self.coordenadas = coordenadas
        self.latitude = latitude
        self.longitude = longitude

myfirstflask/app.py
# -*- coding: utf-8 -*-
from flask.ext.sqlalchemy import SQLAlchemy
from flask import Flask

# App
app = Flask(__name__, instance_relative_config=True)

# Config
app.config.from_object('myfirstflask.config')

# Flask-SQLAlchemy
db = SQLAlchemy(app)

# Automatically create tables
from myfirstflask.models import marker
db.create_all()

# Blueprints
from myfirstflask.routes.app import mod_app
app.register_blueprint(mod_app)

from myfirstflask.routes.marker import mod_marker
app.register_blueprint(mod_marker)

from myfirstflask.routes import errors

myfirstflask/routes/app.py
from flask import Blueprint, render_template

mod_app = Blueprint('mod_app', __name__)


@mod_app.route('/')
def home():
    return render_template('index.html', title='Index')

myfirstflask/routes/errors.py
# -*- coding: utf-8 -*-
from flask import render_template
from myfirstflask.app import app


@app.errorhandler(401)
def unauthorized(error):
    code = '401'
    error = u'Oops! Você não tem autorização'
    return render_template('error.html', error=error, code=code)


@app.errorhandler(404)
def page_not_found(error):
    code = '404'
    error = u'Oops! Página não encontrada.'
    return render_template('error.html', error=error, code=code)


@app.errorhandler(405)
def method_not_allowed(error):
    code = '405'
    error = u'Oops! Método não permitido'
    return render_template('error.html', error=error, code=code)


@app.errorhandler(500)
def internal_server_error(error):
    code = '500'
    error = u'Oops! Erro interno no servidor'
    return render_template('error.html', error=error, code=code)


def error_personalized(error, code):
    return render_template('error.html', error=error, code=code)

myfirstflask/routes/marker.py
from flask import Blueprint, request
from myfirstflask.app import db
from myfirstflask.models.marker import Marker
import json

mod_marker = Blueprint('mod_marker', __name__)


@mod_marker.route('/marker/add', methods=['POST'])
def add_marker():
    #  data = json.loads(request.data.decode('utf-8'))
    data = {
        'lat': request.form.get("lat"),
        'lng': request.form.get("lng")
    }
    marker = Marker(request.form.get("lat"), request.form.get("lng"))
    try:
        db.session.add(marker)
        db.session.commit()
        data['id'] = marker.id
        data['msg'] = "Adicionado com sucesso"
    except Exception as error:
        print(repr(error))
        data['id'] = -1
        data['msg'] = "Não foi possível adicionar o marcador"
    return json.dumps(data), 200


@mod_marker.route('/marker/all')
def all_markers():
    data = [{'id': marker.id, 'lat': marker.latitude, 'lng': marker.longitude}
            for marker in Marker.query.all()]
    return json.dumps(data), 200

myfirstflask/templates/error.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>My First Flask</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo.png') }}">
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <section class="page-error">
        <div class="content container text-center">
            <h2 class="headline" style="color:#0089E1"><b>{{ code }}</b></h2>
            <div class="error-content">
                <h3><b>{{ error }}</b></h3>
                <p><a href="{{ url_for('mod_app.home') }}"><b>Voltar a página inicial</b></a></p>
            </div>
        </div>
    </section>
</body>

</html>

myfirstflask/templates/index.html
{% extends "layout.html" %}

{% block title %}My First Flask{% endblock %}

{% block css%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/leaflet.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/leaflet.draw.min.css') }}">
{% endblock %}

{% block js%}
    <script src="{{ url_for('static', filename='js/leaflet.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/leaflet.draw.2-4.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

{% block content %}
    <div id="map" class="map"></div>
{% endblock %}

myfirstflask/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo.png') }}">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" media="screen" />
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" media="screen" />
    {% block css %}{% endblock%}
</head>

<body>
    <section>
        {% block content %}{% endblock %}
    </section>
</body>
{% block js %}{% endblock%}

</html>